/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewDataHubGUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import NewDataHub.User;

/**
 *
 * @author s3898839
 */
public class NewDataHubGUI extends javax.swing.JFrame {

	/**
	 * Creates new form NewDataHubGUI
	 */

	private ArrayList<Post> posts;
	private ArrayList<User> users;

	private static User currentUser;

	private FileInputStream fis;
	private ObjectInputStream ois;
	private FileOutputStream fos;
	private ObjectOutputStream oos;

	public NewDataHubGUI() {

		posts = new ArrayList<Post>();
		users = new ArrayList<User>();

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Data Hub App");

		btnNewButton = new JButton("Sign up");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent e) {

				String response;
				response = JOptionPane.showInputDialog("Enter a username: ");
				String username = response;

				for (User user : users) {
					if (user.getUsername().equals(username)) {
						System.out.println("Username already taken. Please choose another one.");
						return;
					}
				}

				response = JOptionPane.showInputDialog("Enter a password:  ");
				String password = response;

				response = JOptionPane.showInputDialog("Enter your first name: ");
				String firstName = response;

				response = JOptionPane.showInputDialog("Enter your last name: ");
				String lastName = response;

				User newUser = new User(username, password, firstName, lastName);
				users.add(newUser);

				JOptionPane.showConfirmDialog(null, "Sign up successful! You can now log in.");
			}
		});

		JButton btnNewButton_1 = new JButton("Log In");
		btnNewButton_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String response;
				response = JOptionPane.showInputDialog("Enter a username: ");
				String username = response;

				response = JOptionPane.showInputDialog("Enter a password:  ");
				String password = response;

				for (User user : users) {
					if (user.getUsername().equals(username) && user.getPassword().equals(password)) {
						setCurrentUser(user);

						JOptionPane.showConfirmDialog(null, "Welcome, " + user.getFullName() + "!");
						ProfileMenu.run3();
						return;
					}
				}

				JOptionPane.showConfirmDialog(null, "Invalid username or password. Please try again.");
			}

		});

		btnNewButton_2 = new JButton("exit");
		btnNewButton_2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				JOptionPane.showConfirmDialog(null, "Goodbye!");
				dispose();
				return;

			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(127).addComponent(jLabel1,
								GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addGap(28)
								.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addComponent(btnNewButton_1, GroupLayout.PREFERRED_SIZE, 93,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(btnNewButton_2, GroupLayout.PREFERRED_SIZE, 93,
												GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createSequentialGroup().addGap(39).addComponent(btnNewButton)))
						.addContainerGap(156, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE).addGap(32)
						.addComponent(btnNewButton).addGap(18).addComponent(btnNewButton_1)
						.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(btnNewButton_2)
						.addContainerGap(103, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NewDataHubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NewDataHubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NewDataHubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewDataHubGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NewDataHubGUI().setVisible(true);
			}
		});
	}

	public void UserLists() {
		User[] arrOfUsers = { 
				 User user1 = new User("user1", "password1", "John", "Doe");
			        User user2 = new User("user2", "password2", "Jane", "Smith");
		};
		for (int i = 0; i < arrOfUsers.length; i++) {
			users.add(arrOfUsers[i]);
		}

	public static User getCurrentUser() {
		return currentUser;
	}

	public static void setCurrentUser(User currentUser) {
		NewDataHubGUI.currentUser = currentUser;
	}

	private javax.swing.JLabel jLabel1;
	private JButton btnNewButton;
	private JButton btnNewButton_2;
}
